from django.urls import path, re_path
from .views import *

urlpatterns = [
    # path('add_sql/', add_sql),
    # re_path('^del/(.+)', del_sql, name='del_sql'),
    path('add_admin/', add_admin),
    path('imp/', server_import),
    path('login/', login),
    path('', login),
    path('index/', serverManage, name='index'),
    path('getServerList/', getServerList, name='getServerList'),
    # re_path('^index/(\d+)', index),
    path('add/', server_add, name='add'),
    path('handle_hard/', getSystemInfoHandler, name='handle_hard'),
    path('shell/', serverList, name='shell'),
    re_path('^del/(.+)', server_del, name='del'),
    re_path('^update/(\d+)', server_modify, name='update'),
    path('out/', SignOut),
    path('change/', server_pwd_change, name='change_pwd'),
    re_path('^webssh/(.+)', webssh, name='webssh'),
    path('ufile/', ufile, name='ufile'),
    re_path('^downfile/(.+)', downfile, name='downfile'),
    path('down_handler/', down_handler, name='down_handler'),
    path('tree/', serverListHandler),
    path('linux/', serverBatchRun),
    path('ed_pwd/', modifyUserPassword),
    re_path('^xshell/(.+)', getXshell, name='xshell'),
    re_path('^xftp/(.+)', getXftp, name='xftp'),
    path('project/', project, name='project'),
    path('edit_project/', edit_project, name='edit_project'),
    re_path('^obj_update/', obj_modify, name='obj_update'),
    re_path('^obj_hd/', obj_modify_handler, name='obj_hd'),
    re_path('^obj_del/(\d+)', obj_del, name='obj_del'),
    re_path('^obj_hander/', obj_hander, name='obj_hander'),
    re_path('^queue/', task_queue, name='queue'),
    re_path('^que_del/(\d+)', task_queue_del, name='que_del'),
    path('remark/', remark),
    path('getTemplate/', showServerTemplate, name='getTemplate'),
    path('addTemplate/', addServerTemplate, name='addTemplate'),
    path('delTemplate/', delServerTemplate, name='delTemplate'),
    path('tools/', small_tool, name='tools'),
    path('gettools/', get_tools, name='gettools'),
    path('showDatabase/', showDatabase, name='showDatabase'),
    path('showUrlMgm/', showUrlMgm, name='showUrlMgm'),
    path('showSupervisor/', showSupervisor, name='showSupervisor'),
    path('super/', super_handler, name='super'),
    path('getSuperConf/', getSuperConf, name='getSuperConf'),
    path('searchSuperConf/', searchSuperConf, name='searchSuperConf'),
    path('saveSuperConf/', saveSuperConf, name='saveSuperConf'),
    path('batch_edit/', batch_edit, name='batch_edit'),
    path('getProjectDeploymentRecord/', getProjectDeploymentRecord)

]
