# Generated by Django 2.1.4 on 2018-12-06 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='未分组', max_length=30, verbose_name='名称')),
            ],
        ),
        migrations.CreateModel(
            name='PassWord',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(default='未命名', max_length=30)),
                ('ctime', models.DateTimeField(auto_now=True, null=True)),
                ('system', models.IntegerField()),
                ('ip', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('port', models.IntegerField(default=22)),
                ('user_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Group')),
            ],
        ),
    ]
