# Generated by Django 2.1.4 on 2018-12-06 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=30, verbose_name='分组名称'),
        ),
        migrations.AlterField(
            model_name='group',
            name='uid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='password',
            name='hostname',
            field=models.CharField(default='未命名', max_length=30, verbose_name='主机名'),
        ),
        migrations.AlterField(
            model_name='password',
            name='ip',
            field=models.CharField(max_length=30, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(max_length=20, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='password',
            name='port',
            field=models.IntegerField(default=22, verbose_name='端口'),
        ),
        migrations.AlterField(
            model_name='password',
            name='system',
            field=models.CharField(choices=[('level1', 'Linux'), ('level2', 'Windows'), ('level3', '其他')], max_length=20, verbose_name='系统'),
        ),
        migrations.AlterField(
            model_name='password',
            name='user',
            field=models.CharField(max_length=20, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='password',
            name='user_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Group', verbose_name='分组'),
        ),
    ]
