# Generated by Django 2.1.4 on 2018-12-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20181206_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='hostname',
            field=models.CharField(default='未命名', max_length=30, null=True, verbose_name='主机名'),
        ),
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(max_length=30, null=True, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='password',
            name='port',
            field=models.IntegerField(default=22, null=True, verbose_name='端口'),
        ),
        migrations.AlterField(
            model_name='password',
            name='system',
            field=models.CharField(choices=[('level1', 'Linux'), ('level2', 'Windows'), ('level3', '其他')], default='Linux', max_length=20, verbose_name='系统'),
        ),
    ]
