# Generated by Django 2.1.4 on 2018-12-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.AlterField(
            model_name='users',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
