# Generated by Django 2.1.4 on 2018-12-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20181206_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='hostname',
            field=models.CharField(max_length=30, null=True, verbose_name='主机名'),
        ),
        migrations.AlterField(
            model_name='password',
            name='system',
            field=models.CharField(choices=[('level1', 'Linux'), ('level2', 'Windows'), ('level3', '其他')], default='Linux', max_length=20, null=True, verbose_name='系统'),
        ),
        migrations.AlterField(
            model_name='password',
            name='user',
            field=models.CharField(max_length=20, null=True, verbose_name='用户名'),
        ),
    ]
