# Generated by Django 2.1.4 on 2018-12-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20181207_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.BinaryField(max_length=300, null=True, verbose_name='密码'),
        ),
    ]
