# Generated by Django 2.1.4 on 2018-12-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20181208_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(max_length=300, null=True, verbose_name='密码'),
        ),
    ]
