# Generated by Django 2.1.4 on 2018-12-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20181213_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersgroup',
            name='hostgroup',
        ),
        migrations.AddField(
            model_name='usersgroup',
            name='hostgroup',
            field=models.ManyToManyField(null=True, to='index.Group', verbose_name='分组'),
        ),
    ]
