# Generated by Django 2.1.4 on 2018-12-13 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20181213_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.UsersGroup', verbose_name='分组'),
        ),
    ]
