# Generated by Django 2.1.4 on 2018-12-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20181213_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersgroup',
            name='hostgroup',
            field=models.ManyToManyField(null=True, to='index.Group', verbose_name='机器组'),
        ),
    ]
