# Generated by Django 2.1.4 on 2018-12-13 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20181213_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersgroup',
            old_name='Group',
            new_name='hostgroup',
        ),
    ]
