# Generated by Django 2.1.4 on 2018-12-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_auto_20181213_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': '服务器分组', 'verbose_name_plural': '服务器分组'},
        ),
        migrations.AlterModelOptions(
            name='password',
            options={'verbose_name': '服务器信息', 'verbose_name_plural': '服务器信息'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.AlterModelOptions(
            name='usersgroup',
            options={'verbose_name': '用户组', 'verbose_name_plural': '用户组'},
        ),
        migrations.AddField(
            model_name='usersgroup',
            name='host',
            field=models.ManyToManyField(to='index.PassWord', verbose_name='特定机器'),
        ),
        migrations.AlterField(
            model_name='usersgroup',
            name='hostgroup',
            field=models.ManyToManyField(to='index.Group', verbose_name='机器组'),
        ),
    ]
