# Generated by Django 2.1.4 on 2018-12-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_auto_20181214_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='cpu_info',
            field=models.CharField(max_length=100, null=True, verbose_name='cpu信息'),
        ),
        migrations.AddField(
            model_name='password',
            name='hard_info',
            field=models.CharField(max_length=100, null=True, verbose_name='硬盘信息'),
        ),
        migrations.AddField(
            model_name='password',
            name='mem_info',
            field=models.CharField(max_length=100, null=True, verbose_name='内存信息'),
        ),
        migrations.AddField(
            model_name='password',
            name='system_info',
            field=models.CharField(max_length=20, null=True, verbose_name='系统版本'),
        ),
    ]
