# Generated by Django 2.1.4 on 2018-12-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_auto_20181219_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='status',
            field=models.CharField(max_length=100, null=True, verbose_name='状态'),
        ),
    ]
