# Generated by Django 2.1.4 on 2018-12-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_password_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='cpu_count',
            field=models.CharField(max_length=100, null=True, verbose_name='cpu核心数'),
        ),
    ]
