# Generated by Django 2.1.4 on 2019-01-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_password_cpu_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostTmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('unique', models.CharField(max_length=40, unique=True)),
                ('host', models.CharField(max_length=32)),
                ('port', models.IntegerField()),
                ('user', models.CharField(max_length=32)),
                ('auth', models.CharField(max_length=16)),
                ('pkey', models.TextField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=180, null=True)),
            ],
        ),
    ]
