# Generated by Django 2.1.4 on 2019-01-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_hosttmp'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='normal_pwd',
            field=models.CharField(max_length=300, null=True, verbose_name='密码'),
        ),
        migrations.AddField(
            model_name='password',
            name='normal_user',
            field=models.CharField(max_length=20, null=True, verbose_name='用户名'),
        ),
    ]
