# Generated by Django 2.1.4 on 2019-02-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_auto_20190125_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('obj_name', models.CharField(max_length=30)),
                ('obj_text', models.TextField()),
            ],
        ),
    ]
