# Generated by Django 2.1.4 on 2019-02-26 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_object'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='uid',
            new_name='obj_uid',
        ),
    ]
