# Generated by Django 2.1.4 on 2019-02-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_auto_20190226_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='obj_uid',
            new_name='uid',
        ),
        migrations.AlterField(
            model_name='object',
            name='obj_name',
            field=models.CharField(max_length=50),
        ),
    ]
