# Generated by Django 2.1.4 on 2019-03-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0024_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
