# Generated by Django 2.1.4 on 2019-03-01 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0025_queue_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='remark',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('rep', models.TextField()),
                ('host', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.PassWord')),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='remark',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.remark'),
        ),
    ]
