# Generated by Django 2.1.4 on 2019-03-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0027_auto_20190301_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remark',
            name='host',
        ),
        migrations.AddField(
            model_name='remark',
            name='host',
            field=models.ManyToManyField(to='index.PassWord', verbose_name='对应机器'),
        ),
    ]
