# Generated by Django 2.1.4 on 2019-03-01 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0028_auto_20190301_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remark',
            name='host',
        ),
        migrations.AddField(
            model_name='remark',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.PassWord', verbose_name='对应机器'),
        ),
    ]
