# Generated by Django 2.1.4 on 2019-03-01 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0029_auto_20190301_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='remark',
        ),
        migrations.AddField(
            model_name='users',
            name='remark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.remark', verbose_name='备注信息'),
        ),
    ]
