# Generated by Django 2.1.4 on 2019-03-01 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0030_auto_20190301_1950'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='remark',
            new_name='remarks',
        ),
    ]
