# Generated by Django 2.1.4 on 2019-03-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0033_auto_20190301_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='remark',
        ),
        migrations.AddField(
            model_name='users',
            name='remark',
            field=models.ManyToManyField(to='index.remarks', verbose_name='备注信息'),
        ),
    ]
