# Generated by Django 2.1.4 on 2019-04-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0034_auto_20190301_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='hostname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
