# Generated by Django 2.1.4 on 2019-04-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0035_queue_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='obj_log',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='password',
            name='cpu_count',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='cpu核心数'),
        ),
        migrations.AlterField(
            model_name='password',
            name='cpu_info',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='cpu信息'),
        ),
        migrations.AlterField(
            model_name='password',
            name='hard_info',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='硬盘信息'),
        ),
        migrations.AlterField(
            model_name='password',
            name='hostname',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='主机名'),
        ),
        migrations.AlterField(
            model_name='password',
            name='mem_info',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='内存信息'),
        ),
        migrations.AlterField(
            model_name='password',
            name='normal_pwd',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='password',
            name='normal_user',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='password',
            name='port',
            field=models.IntegerField(blank=True, default=22, null=True, verbose_name='端口'),
        ),
        migrations.AlterField(
            model_name='password',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='password',
            name='system_info',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='系统版本'),
        ),
        migrations.AlterField(
            model_name='password',
            name='user',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='用户名'),
        ),
    ]
