# Generated by Django 2.1.4 on 2019-04-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0036_auto_20190412_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersgroup',
            name='host',
            field=models.ManyToManyField(blank=True, to='index.PassWord', verbose_name='特定机器'),
        ),
        migrations.AlterField(
            model_name='usersgroup',
            name='hostgroup',
            field=models.ManyToManyField(blank=True, to='index.Group', verbose_name='机器组'),
        ),
    ]
