# Generated by Django 2.1.4 on 2019-04-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0037_auto_20190412_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='linuxTemplate',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
    ]
