# Generated by Django 2.1.4 on 2019-04-19 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0038_linuxtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='dataBase',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='名称')),
                ('ip', models.CharField(max_length=50, verbose_name='ip')),
                ('normal_user', models.CharField(blank=True, max_length=50, null=True, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=50, null=True, verbose_name='密码')),
                ('port', models.CharField(blank=True, max_length=10, null=True, verbose_name='端口')),
                ('remark', models.CharField(blank=True, max_length=50, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='dataBaseGroup',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='名称')),
            ],
        ),
        migrations.AddField(
            model_name='database',
            name='dataGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.dataBaseGroup', verbose_name='分组'),
        ),
    ]
