# Generated by Django 2.1.4 on 2019-04-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0039_auto_20190419_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='database',
            old_name='normal_user',
            new_name='user',
        ),
        migrations.AddField(
            model_name='database',
            name='edition',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='版本'),
        ),
    ]
