# Generated by Django 2.1.4 on 2019-04-19 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0040_auto_20190419_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='databasegroup',
            options={'verbose_name': '服务器信息', 'verbose_name_plural': '服务器信息'},
        ),
    ]
