# Generated by Django 2.1.4 on 2019-04-19 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0041_auto_20190419_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='database',
            options={'verbose_name': '数据库信息', 'verbose_name_plural': '数据库信息'},
        ),
        migrations.AlterModelOptions(
            name='databasegroup',
            options={'verbose_name': '数据库类型', 'verbose_name_plural': '数据库类型'},
        ),
    ]
