# Generated by Django 2.1.4 on 2019-04-19 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0042_auto_20190419_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queue',
            options={'verbose_name': '队列信息', 'verbose_name_plural': '队列信息'},
        ),
        migrations.AlterModelOptions(
            name='remarks',
            options={'verbose_name': '备注信息', 'verbose_name_plural': '备注信息'},
        ),
    ]
