# Generated by Django 2.1.4 on 2019-04-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0043_auto_20190419_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='intranet_ip',
            field=models.CharField(default=1, max_length=30, verbose_name='IP地址'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='password',
            name='ip',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='IP地址'),
        ),
    ]
