# Generated by Django 2.1.4 on 2019-04-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0044_auto_20190422_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='intranet_ip',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='IP地址'),
        ),
    ]
