# Generated by Django 2.1.4 on 2019-04-24 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0045_auto_20190423_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.PassWord', verbose_name='服务器')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Object', verbose_name='模板')),
            ],
            options={
                'verbose_name': '项目部署',
                'verbose_name_plural': '项目部署',
            },
        ),
    ]
