# Generated by Django 2.1.4 on 2019-04-24 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0046_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='object',
            options={'verbose_name': '项目模板', 'verbose_name_plural': '项目模板'},
        ),
    ]
