# Generated by Django 2.1.4 on 2019-04-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0047_auto_20190424_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50, verbose_name='项目名称'),
        ),
    ]
